# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 181fb7a59863dbebb9fe3a9bbdef454c61a283769902690b83ff103bfefdafe06ff683e0f73fa8eba908985b3e10200f66bbc13b20c746738cee0c8e89f8a5f4

test:
  secret_key_base: 391a30fa95741335264a2d03e64d2eec59f44ac2deeede33399d1a94db03279d67046d0ef5f92ff1e95661798d889117a762aef3ceb4c5149b24eb73446df2d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: b2bad385296967a9d0983b4f4da780e9ae508eb05893317e07b8b25a3d13788f13eebcb85ee110550394395606390e1926309d575adb99a39d58c8767090a657
